### ISSUE TITLE
根据这个仓库做了一个题库小程序

### ISSUE THREAD

**Issue by cfeibiao** [ztianming/xuexi.cn#11]
![image](https://user-images.githubusercontent.com/3081773/233526916-072e15bf-2f16-48a7-8ac4-f2a1f3ccb6f8.png)

**Comment by ztianming** [comment]
👍

**Comment by BBSMLtd** [comment]
厉害 可以根据前后首拼确定答案吗？

**Comment by cfeibiao** [comment]
> 厉害 可以根据前后首拼确定答案吗？

![image](https://user-images.githubusercontent.com/3081773/113672205-feb8c380-96e9-11eb-8c2e-7360c463f7da.png)
你的想法跟这个用户是一样吗？如果是的话，我可以试着加一下

**Comment by BBSMLtd** [comment]
> > 厉害 可以根据前后首拼确定答案吗？
> 
> ![image](https://user-images.githubusercontent.com/3081773/113672205-feb8c380-96e9-11eb-8c2e-7360c463f7da.png)
> 你的想法跟这个用户是一样吗？如果是的话，我可以试着加一下

对 之前我用过类似的小程序 但是后来停了 非常好用

**Comment by cfeibiao** [comment]
> > > 厉害 可以根据前后首拼确定答案吗？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/3081773/113672205-feb8c380-96e9-11eb-8c2e-7360c463f7da.png)
> > 你的想法跟这个用户是一样吗？如果是的话，我可以试着加一下
> 
> 对 之前我用过类似的小程序 但是后来停了 非常好用

用拼字首字母搜索题目的功能刚加上了，欢迎大家体验。

**Comment by HolenZhou** [comment]
> > > > 厉害 可以根据前后首拼确定答案吗？
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/3081773/113672205-feb8c380-96e9-11eb-8c2e-7360c463f7da.png)
> > > 你的想法跟这个用户是一样吗？如果是的话，我可以试着加一下
> > 
> > 
> > 对 之前我用过类似的小程序 但是后来停了 非常好用
> 
> 用拼字首字母搜索题目的功能刚加上了，欢迎大家体验。

体验了下，根据首字母拼音检索没问题，但是点进答案详情，所以错了一位，比如我搜的题是2301，点击搜索结果，显示的是2302的题目

**Comment by hupo376787** [comment]
搜到题，看不到答案。只能挨个选项点击才知道

**Comment by cfeibiao** [comment]
> > > > > 厉害 可以根据前后首拼确定答案吗？
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/3081773/113672205-feb8c380-96e9-11eb-8c2e-7360c463f7da.png)
> > > > 你的想法跟这个用户是一样吗？如果是的话，我可以试着加一下
> > > 
> > > 
> > > 对 之前我用过类似的小程序 但是后来停了 非常好用
> > 
> > 
> > 用拼字首字母搜索题目的功能刚加上了，欢迎大家体验。
> 
> 体验了下，根据首字母拼音检索没问题，但是点进答案详情，所以错了一位，比如我搜的题是2301，点击搜索结果，显示的是2302的题目

部分题目确实是编号错位了，是数据格式化出了点问题导致，目前已经修复好重新上线了

**Comment by cfeibiao** [comment]
> 搜到题，看不到答案。只能挨个选项点击才知道

目前做了一点优化，答案会以绿色标记出来

**Comment by hupo376787** [comment]
> > 搜到题，看不到答案。只能挨个选项点击才知道
> 
> 目前做了一点优化，答案会以绿色标记出来

谢谢大佬，辛苦了

**Comment by ZeroX1ng** [comment]
这个题库感觉还是缺了很多题目，建议弄个题目提交入口，大家一起完善造福后人

**Comment by cfeibiao** [comment]
> 这个题库感觉还是缺了很多题目，建议弄个题目提交入口，大家一起完善造福后人

大家可以把题目提到当前仓库，后面我定时去同步到小程序里
